### ISSUE TITLE
how to add IPv6 rule?

### ISSUE THREAD

**Issue by TiloGit** [ibm-cloud-docs/vpc-infrastructure-cli-plugin#2]
https://cloud.ibm.com/docs/vpc?topic=vpc-infrastructure-cli-plugin-vpc-reference#security-group-rule-add

how to add IPv6 rule?

**Comment by lilorozco** [comment]
Hi. 

IPv6 is not supported at the moment. Thank you for your inquiry.

**Comment by TiloGit** [comment]
thanks for the quick reply. please add this current limitation to the linked documentation.

**Comment by lilorozco** [comment]
We do have it documented here https://cloud.ibm.com/docs/vpc?topic=vpc-limitations but will analyze to see if we need to mention this in more places. Thank you!
