### ISSUE TITLE
Broken link for: onboarding software to your account hyperlink

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/vpc-infrastructure-cli-plugin#9]
https://cloud.ibm.com/docs/vpc?topic=vpc-vpc-reference#vpc-reference

broken link for: onboarding software to your account hyperlink
![image](https://user-images.githubusercontent.com/131889203/234650778-96959b83-f890-43f9-8b2b-8039557a3777.png)

![image](https://user-images.githubusercontent.com/131889203/234650808-8c001cb1-17b4-46e1-b103-d1341af450fc.png)

**Comment by vickmuir** [comment]
The link is no longer broken, but it has an incorrect title. I will submit a separate PR to fix that.

**Comment by jmilst** [comment]
PR approved and merged
